os: linux

language: java
services:
  - docker
cache: bundler
dist: bionic

install: skip

jobs:
  include:
    - name: long-running-task
      script:
        - echo "Starting long-running task..."
        - for i in {1..35}; do
            echo "Running... $((i * 60)) seconds elapsed";
            sleep 60;
          done
        - echo "Task completed!"

after_success:
  - echo "done"
  - echo $TRAVIS_TEST_RESULT





  

  

