os: linux


language: java
services:
  - docker
cache: bundler
dist: bionic

install: skip

stages:
  - Tests
  - deploy

jobs:
  include:
    - name: failing
      script: true

    - stage: Tests
      name: "Unit Tests"
      script: ./unit-tests

    - stage: Tests
      name: "Integration Tests"
      script: ./integration-tests

    - stage: deploy
      name: "Deploy to GCP"
      script: ./deploy

after_success:
  - echo done
  - echo $TRAVIS_TEST_RESULT

after_failure:
  - echo failed
  - echo $TRAVIS_TEST_RESULT

  
  
  
  
  
  

  
  
  

  
  
  
  
  

  
  
  
  

  


  
  

  
  





  

  

