os: linux

language: java
services:
  - docker
cache: bundler
dist: bionic

install: skip

jobs:
  include:
    - name: long-running-task
      script:
        - echo "Starting long-running task..."
        - sleep 2400  # 2400 seconds = 40 minutes
        - echo "Task completed!"

after_success:
  - echo "done"
  - echo $TRAVIS_TEST_RESULT




  

  

