os: linux

language: java
services:
  - docker
cache: bundler
dist: bionic

install: skip

stages:
  - test
  - deploy

jobs:
  include:
    - name: failing
      script: true

    - stage: test
      script: ./test 1

    - script: ./test 2  # stage name not required, continues under `test`

    - stage: deploy
      script: ./deploy

after_success:
  - echo done
  - echo $TRAVIS_TEST_RESULT

after_failure:
  - echo failed
  - echo $TRAVIS_TEST_RESULT

  
  
  
  
  
  

  
  
  

  
  
  
  
  

  
  
  
  

  


  
  

  
  





  

  

