os: linux

language: java
services:
  - docker
cache:
  directories:
    - $HOME/.m2   # Cache Maven dependencies (if using Maven)
    - $HOME/.gradle # Cache Gradle dependencies (if using Gradle)
dist: bionic

install: skip

jobs:
  include:
    - name: failing
      script:
        - echo "Running tests"
        - ./gradlew test # Replace with `mvn test` if using Maven

after_success:
  - echo "Build succeeded"
  - echo $TRAVIS_TEST_RESULT

after_failure:
  - echo "Build failed"
  - echo $TRAVIS_TEST_RESULT

  
  

  
  
  
  
  

  
  
  
  

  


  
  

  
  





  

  

